#!/bin/bash

function stakepool_info {
    METADATA="${WORK_DIR}/${CARDANO_NETWORK}-staking/metadata.json"
    if [ -f "${METADATA}" ]; then
        
        POOL_NAME=$(jq -r '.name' $METADATA)
        POOL_DESCRIPTION=$(jq -r '.description' $METADATA)
        POOL_TICKER=$(jq -r '.ticker' $METADATA)
        POOL_HOMEPAGE=$(jq -r '.homepage' $METADATA)

        echo "Pool Name: ${POOL_NAME}"
        echo "Pool Description: ${POOL_DESCRIPTION}"
        echo "Pool Ticker: ${POOL_TICKER}"
        echo "Pool Homepage: ${POOL_HOMEPAGE}"
    fi

    echo "Pool Pledge: ${poolPledge}"
    echo "Pool Cost: ${poolCost}"
    echo "Pool Margin: ${poolMargin}"
}