#!/bin/bash

function wait_for_socket {
    slot=$("${SRC_DIR}/relay_get_slot")
    if [[ -z "$slot" ]]; then
        echo -e "\nWaiting for cardano-node to read the blockchain and start the socket."
        echo -n "It may take a while. Trying again."
        sleep 5

        while true; do
            slot=$("${SRC_DIR}/relay_get_slot")
            if [[ -z "$slot" ]]; then
                echo -n "."
                sleep 5
            else
                break
            fi
        done
        echo -e "${CHECK_MARK} Socket is now functional."
    fi
}
