#!/bin/bash

function wait_for_sync {
    source "${SRC_DIR}/functions/wait_for_socket"
    wait_for_socket
    WAIT_FOR_SYNC=$1

    echo -e "\nWaiting for cardano-node to sync to at least ${WAIT_FOR_SYNC}%"
    echo -n ""

    while true; do
        status=$("${SRC_DIR}/relay_sync_status")
        SYNC_PCT=$( echo $status | tr ' ' '\n' | tail -1 | sed 's/%//g' | bc)
        echo -en "\\r== $status"

        if [[ (($SYNC_PCT > $WAIT_FOR_SYNC)) ]]; then
            echo -e "${CHECK_MARK} Done."
            break
        fi
        sleep 5
    done
}
