#!/bin/bash
# Thanks to Smaug from https://t.me/CardanoStakePoolWorkgroup
# This command check the sync status of a node relay

source "${SRC_DIR}/functions/wait_for_socket"
wait_for_socket

GENESIS="${WORK_DIR}/config/${CARDANO_NETWORK}net-shelley-genesis.json"
BYRON_GENESIS="${WORK_DIR}/config/${CARDANO_NETWORK}net-byron-genesis.json"

epoch_length=$(jq -r .epochLength $GENESIS)
slot_length=$(jq -r .slotLength $GENESIS)
byron_slot_length=$(( $(jq -r .blockVersionData.slotDuration $BYRON_GENESIS) / 1000 ))
byron_epoch_length=$(( $(jq -r .protocolConsts.k $BYRON_GENESIS) * 10 ))

byron_start=$(jq -r .startTime $BYRON_GENESIS)
byron_end=$((byron_start + HARDFORK_EPOCH * byron_epoch_length * byron_slot_length))
byron_slots=$(($HARDFORK_EPOCH * byron_epoch_length))
now=$(date +'%s')

expected_slot=$((byron_slots + (now - byron_end) / slot_length))
current_slot=$(docker run --interactive \
    --env CARDANO_NODE_SOCKET_PATH=/node/node.socket \
    --volume "${WORK_DIR}/${CARDANO_NETWORK}-relay:/node" \
    --volume ${walletFolder}:/root \
    --workdir /root \
    genzbank/cardano-cli \
        query tip $NETWORK_ARGUMENT | jq -r '.slot')
percent=$(echo -e "scale=2\n$current_slot * 100 / $expected_slot" | bc)

echo "slot ${current_slot}/${expected_slot} ${percent}%"
