#!/bin/bash
SLOT=$(docker run --interactive \
    --env CARDANO_NODE_SOCKET_PATH=/node/node.socket \
    --volume "${WORK_DIR}/${CARDANO_NETWORK}-relay:/node" \
    --volume $PWD:/root \
    --workdir /root \
    genz-pool/cardano-cli \
      query tip --mainnet | jq -r '.slot')
echo "${SLOT}"
