#!/bin/bash

if [ -z "$name" ]; then
	export name="main"
fi

# Check for required files
if [ ! -f "${WORK_DIR}/wallets/${name}/payment.addr" ]; then
    echo "Missing required payment.addr. You need to run \`wallet create --name ${name}\` to generate this key."
    echo "Or use \`--name wallet_name\` to select an existed wallet."
    exit 3 #TODO $ERROR_CODE_MISSING
fi

# Wait for node to sync
if [[ "${WAIT_FOR_SYNC}" == "True" ]]; then
   # wait_for_sync 99.90
   echo "Wait for sync is not supported."
   exit 1
fi

ADDRESS=$(cat "${WORK_DIR}/wallets/${name}/payment.addr")

docker run --interactive \
    --env CARDANO_NODE_SOCKET_PATH=/node/node.socket \
    --volume "${WORK_DIR}/${CARDANO_NETWORK}-relay:/node" \
    --volume $PWD:/root \
    --workdir /root \
    genzbank/cardano-cli \
        query utxo ${NETWORK_ARGUMENT} \
        --address ${ADDRESS}
