#!/bin/bash

# From Documentation
# https://github.com/input-output-hk/cardano-tutorials/blob/master/node-setup/040_transactions.md
# https://github.com/input-output-hk/cardano-tutorials/blob/master/node-setup/050_register_key.md

# Init functions and vars

# Define wallet
if [ -z "$name" ]; then
    export name="main"
fi

walletFolder="${WORK_DIR}/wallets/${name}"
if [ ! -d "$walletFolder" ]; then
    echo "Wallet not found. Use \' wallet create --name $name \' to create a new one"
    exit 3 # TODO: replace with error code
fi

# Enter staking directory
STAKE_ADDR=$(cat "${walletFolder}/stake.addr")

echo ""
echo "Checking staking addresses for $name."

# Check for required files
files=( \
 "stake.vkey" \
 "stake.skey" \
 "payment.skey" \
 "payment.addr" \
)
for file in "${files[@]}"
do 
    if [ ! -f "${walletFolder}/${file}" ]; then
        echo ${walletFolder}/$file    
        echo "Missing required ${file}. You need to run \`wallet create ${name}\` to generate this key."
        exit 3 # TODO: replace with error code
    fi
done

docker run --interactive \
    --env CARDANO_NODE_SOCKET_PATH=/node/node.socket \
    --volume "${WORK_DIR}/${CARDANO_NETWORK}-relay:/node" \
    --volume "$WORK_DIR:/root" \
    --workdir /root \
    genzbank/cardano-cli \
       query stake-address-info \
       --address ${STAKE_ADDR} \
       ${NETWORK_ARGUMENT}